### ISSUE TITLE
Non-G20 countries

### ISSUE THREAD

**Issue by nicholasdavies** [datasciencecampus/google-mobility-reports-data#2]
Hi there,

This is really useful, thanks for doing this. Is there any chance you could provide processed CSVs for all countries, rather than just G20 countries?

Thanks,

Nick

**Comment by N-FK** [comment]
Hi,

great work. I second Nick - having more countries would be awesome.

**Comment by mshodge** [comment]
Hi both. We have a tool (in the README) of this repository that shows you how to gather the data for other countries. Let me know if you have any issues, or cannot use the tool. The data in this repository has been sense checked, and we don't have the resources to do it for all other countries. However, we may be able to convert the data with the caveat that it isn't sense checked and should it be used, it should be used with precaution.

**Comment by thijsniks** [comment]
Unaudited data would already be helpful!

Does the audit process consist of visually confirming that the graphs match up? If so, I’m pretty sure we can get some extra eyes to help out with the auditing.

**Comment by NicolasWoloszko** [comment]
I second thijsniks. 
Many people out there ready to eyeball the extracts but not to use your python tool. 
Thanks a lot for this !

**Comment by mshodge** [comment]
Hi both. Google have released the data as a CSV file now. 

https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv
